### ISSUE TITLE
Is there a way to add -crossplay flag so users from Epic can join?

### ISSUE THREAD

**Issue by leemmcc** [Hermsi1337/docker-ark-server#13]
Getting this up and running was pretty easy, but I can't figure out the proper way to add the -crossplay flag so epic users can join as well (or only).

**Comment by Hermsi1337** [comment]
Right now there is no way to adjust start-parameters.. but that's a pretty good idea...

I will take care of this asap

**Comment by Hermsi1337** [comment]
Hey @leemmcc, can you try to use the current `latest` tag? `latest-1629797564`

You should now be able to add `command: -crossplay` to your `docker-compose.yml`.  
This flag is then passed to `arkmanager run` which then adds the flag to the ark-server.

Let me know if that works for you (=

**Comment by theryanb** [comment]
Hey, firstly thanks for you share. I have the same problem, i did what you said but my friend cant see the server on epic game lobby. Maybe i have misplaced « command: -crossplay » in the docker-compose.yml. I dit that:


version: '3'

services:
  server:
    restart: always
    container_name: ark_server
    image: hermsi/ark-server:latest-1629797564
    volumes:
      - ……..
    command: -crossplay
    environment:
      - TZ=EUROPE/London

**Comment by Hermsi1337** [comment]
Hey @theryanb, I did some more research on this..
Could you try the following ?

```yaml
command: --arkopt,--crossplay
```

**Comment by halkeye** [comment]
Btw i had success with crossplay with. (battleye will kick epic players every like 5 min)

```
    command: --arkopt,-crossplay --arkopt,-NoBattlEye
```

**Comment by Hermsi1337** [comment]
I'll close this issue. Feel free to re-open as soon as you're experiencing issues.
