### ISSUE TITLE
Readme outdated on Docker Hub

### ISSUE THREAD

**Issue by Skaronator** [Hermsi1337/docker-ark-server#19]
Just a quick headsup the Readme on Docker Hub seems to be outdated. The docker-compose example uses the same port twice:

```yaml
    ports:
      # Port for connections from ARK game client
      - "7778:7778/udp"
      # Raw UDP socket port (always Game client port +1)
      - "7778:7778/udp"
```

https://hub.docker.com/r/hermsi/ark-server

**Comment by Hermsi1337** [comment]
Woops, you're right. I forgot that there is no automated updated since `dockerhub` has changed it's pricing-model.

I'll update it, tanks!
