### ISSUE TITLE
How would I make this load Crystal Isle map

### ISSUE THREAD

**Issue by prozacgod** [Hermsi1337/docker-ark-server#21]
I'm not sure how to configure this to load the crystal isle map.

Do I need to send in a AST command or configure some other file?

ATM I created a simple utilty script to enable all of my mods and I just sorta assumed perhaps Crystal Isle was treaded like a mod?

so I did this ./arkmanager enablemod CrystalIsles

(arkmanager just docker-composes and runs arkmanager in the  docker instance)

**Comment by prozacgod** [comment]
Also how do I setup multipliers, I'd also like to adjust the inventory stack size  - https://steamcommunity.com/sharedfiles/filedetails/?id=761535755

I know the above is probably a bit outt of scope but figured you/someone here may know

The mod author suggests there's a configuration file to modify to get this to work.

> Remember that ARK itself does support stacking through the game.ini (with some limitations).

**Comment by ThePowershellNinja** [comment]
@prozacgod, Inventory stack size can be set in the gameusersettings.ini.  

This is what my servers are set to:
`ItemStackSizeMultiplier=5.000000`

<br>

See [https://ark.fandom.com/wiki/Server_configuration](https://ark.fandom.com/wiki/Server_configuration) for all the settings that you can configure your server with. Note that settings will go into one of these two files:
- /app/server/ShooterGame/Saved/Config/LinuxServer/Game.ini
- /app/server/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini


As far as the map goes, Crystal Isles is now an official map. You should be able to use this flag when you initialize your docker container per the documentation. If you are using docker compose plug it into the environment section. If you are using `docker run`, then add this to your command line:
`-e SERVER_MAP="CrystalIsles"`
