### ISSUE TITLE
libcurl.so:cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Nirflysher** [Hermsi1337/docker-ark-server#22]
Hello,
I'm trying to run this on Synology Docker and getting the following error on libcurl
Am I missing something on the installation process ?

______________________________________
# Ark Server - Tue 30 Nov 2021 09:02:13 PM UTC
# UID 1000 - GID 1000
______________________________________
Setting up folder and file structure...
No game files found. Installing...
Running command 'install' for instance 'main'
Installing ARK server ...   - / | \ - / | \ - / | \ - / | \ - / | \ - / | \ - / | \ - / | \ - / | \ - / | \ - / | \ - / | \ - / | \ - / | \ - / | \ - / | \ - / | \ - / | \ - / | \ - / | \ - / | \assert_20211130210255_6.dmp[114]: Uploading dump (out-of-process)
/tmp/dumps/assert_20211130210255_6.dmp
assert_20211130210255_6.dmp[114]: Finished uploading minidump (out-of-process): success = no
assert_20211130210255_6.dmp[114]: error: libcurl.so: cannot open shared object file: No such file or directory
assert_20211130210255_6.dmp[114]: file ''/tmp/dumps/assert_20211130210255_6.dmp'', upload no: ''libcurl.so: cannot open shared object file: No such file or directory''
No crontab set
Running command 'run' for instance 'main'
2021-11-30 21:02:55: start
2021-11-30 21:02:55: Running /app/server/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?SessionName=Flysher\?ServerPassword\?ServerAdminPassword=cc\?MaxPlayers=20\?GameModIds\?GameModIds\?RCONEnabled=True\?ServerPassword\?listen -log -log
/usr/local/bin/arkmanager: line 1289: /app/server/ShooterGame/Binaries/Linux/ShooterGameServer: Permission denied
2021-11-30 21:02:55: Server PID: 148
2021-11-30 21:03:00: Bad PID ''; expected '148'
2021-11-30 21:03:00: exited with status 0

**Comment by Nirflysher** [comment]
I just found out that my docker was blocked by my firewall.
I've added an exception on the firewall rules and now it's downloading the game files properly.

**Comment by bzyg7b** [comment]
> I just found out that my docker was blocked by my firewall. I've added an exception on the firewall rules and now it's downloading the game files properly.

Hey, was this your network firewall or something on the machine running docker?
