### ISSUE TITLE
mkdir: cannot create directory ‘/app/log’: Permission denied

### ISSUE THREAD

**Issue by sudoxroot** [Hermsi1337/docker-ark-server#27]
# Ark Server - Thu 30 Dec 2021 11:16:06 PM UTC

# UID 1000 - GID 1000

# ARGS 

_______________________________________

Setting up folder and file structure...

mkdir: cannot create directory ‘/app/log’: Permission denied

**Comment by jstnmthw** [comment]
Make sure the user who controls the docker container has access that folder on the local drice. In my case, the user was `ubuntu` but the folder created was owned by `root`, Once I changed ownership, the permissions issues went away.

**Comment by Hermsi1337** [comment]
With #25 the `entrypoint.sh` ensures correct rights on the `app`-dir when starting.

This should fix your issue (=
