### ISSUE TITLE
Help: cp: cannot stat '/home/steam/arkmanager.cfg': No such file or directory

### ISSUE THREAD

**Issue by bachi76** [Hermsi1337/docker-ark-server#32]
Hi, a poor soul of a dadmin here that doesn't know Ark but was tasked to setup a server ...
I tried the docker-compose in ./deploy, but get the error below. I guess I am missing something? Do I need to setup something to make it happen? What, exactly?

> bachi@brain2:~/ark-server/deploy$ docker-compose up
> Creating network "ark_default" with the default driver
> Pulling server (hermsi/ark-server:latest)...
> latest: Pulling from hermsi/ark-server
> 72a69066d2fe: Pull complete
> fa498f734cfb: Pull complete
> ee860d226a10: Pull complete
> 5233409ddbc7: Pull complete
> 043a1fae8f45: Pull complete
> Digest: sha256:8778a2bcc5daf72d7457bffdb4306eb08c1a616ff3d2d91bef0f494786e11c1e
> Status: Downloaded newer image for hermsi/ark-server:latest
> Creating ark_server ... done
> Attaching to ark_server
> server_1  | _______________________________________
> server_1  | 
> server_1  | # Ark Server - Mon 03 Jan 2022 05:06:33 PM UTC
> server_1  | # UID 1000 - GID 1000
> server_1  | # ARGS 
> server_1  | _______________________________________
> server_1  | Setting up folder and file structure...
> server_1  | **cp: cannot stat '/home/steam/arkmanager.cfg': No such file or directory**
> server_1  | cp: cannot stat '/home/steam/arkmanager.cfg': No such file or directory
> ark_server exited with code 1

**Comment by glazeddonut** [comment]
Same here ...

**Comment by Hermsi1337** [comment]
I will check this.

Until this is fixed, use tag latest-1640667787:

docker pull hermsi/ark-server:latest-1640667787


Regards

**Comment by Hermsi1337** [comment]
This should be fixed by #25
