### ISSUE TITLE
ensure_rights preventing boot with readonly configmap

### ISSUE THREAD

**Issue by viruzeno** [Hermsi1337/docker-ark-server#34]
I am deploying on Kuberneties and have made the file '/app/server/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini' a ConfigMap. 
This means its readonly, and the chown command you added in recently can't modify it. (entrypoint.sh:14)

Reverting back to 'hermsi/ark-server:latest-1639458184' has fixed my issue, but this may effect others.

```
...ensuring rights on /app /home/steam
chown: changing ownership of '/app/server/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini': Read-only file system
```

**Comment by Hermsi1337** [comment]
This is indeed a problem. I think I will add `|| return` as a "quick" fix for you.
