### ISSUE TITLE
Misisng files in docker image

### ISSUE THREAD

**Issue by VIPKaiser** [Hermsi1337/docker-ark-server#39]
There seems to be files missing from the docker install /app/server/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini: No such file or directory cannot start the server.

**Comment by VIPKaiser** [comment]
My bad, didn't realise you had to also do docker exec ark_server arkmanager install as well once the docker was up and running. Thanks for your hard work with putting this together.

**Comment by Hermsi1337** [comment]
Hey mate, I'm glad you fixed your issue.

In general it should not be required to exec an install on your own after starting your container.

Can you provide some more information regarding your setup? E.g. `docker-compose.yml` or your `docker run`-command?

**Comment by VIPKaiser** [comment]
Yes of course mate. I'm using docker compose. I've removed the docker container, the directory and image and tried it again but the only way I can get it to run is by doing "docker exec ark_server arkmanager install"... not sure what i'm doing wrong.

version: "3"

services:
 ark_server:
    image: hermsi/ark-server:latest
    networks:
      - local
    container_name: ark_server
    environment:
      - SESSION_NAME="KaiserARK"
      - SERVER_MAP="TheIsland"
      - SERVER_PASSWORD=""
      - ADMIN_PASSWORD="*******"
      - MAX_PLAYERS="100"
      - UPDATE_ON_START="false"
      - BACKUP_ON_STOP="true" 
      - PRE_UPDATE_BACKUP="true"
      - WARN_ON_STOP="true"
      - GAME_CLIENT_PORT="7777"
      - UDP_SOCKET_PORT="7778"
      - RCON_PORT="27020"
      - SERVER_LIST_PORT="27015"
    volumes:
      - /home/docker/ark_server/:/app
      - /home/docker/ark_server/backup/:/ARK-backups
    ports:
      - 7777:7777/udp
      - 7778:7778/udp
      - 27020:27020/tcp
      - 27015:27015/udp
    restart: unless-stopped
