### ISSUE TITLE
Container Lifetime Tied to Arkmanager

### ISSUE THREAD

**Issue by suhaibmalik** [Hermsi1337/docker-ark-server#4]
Hard to tell whether this is an issue with arkmanager or the image. But, the issue is that it's impossible to update the server from within the container. As a part of the `arkmanager update` process, the arkmanager process is killed. This also kills the container.

Two possible fixes:
1. Either the container lifetime needs to be disassociated from the arkmanager process (bad for resiliency) or abstracted away from it to allow for the container lifetime to live through an update, or
1. Updates should be part of the container entrypoint so that you can simply restart the container to update.

Edit:
The distinction is highlighted in the use of `arkmanager run` as opposed to `arkmanager start`. See: https://github.com/arkmanager/ark-server-tools#commands-acting-on-instances

**Comment by suhaibmalik** [comment]
I'm not totally sure about what all this affects but this PR has, at least, allowed us to update the ark server: https://github.com/Hermsi1337/docker-ark-server/pull/5

**Comment by Hermsi1337** [comment]
Hey m8,

there is already an env-var called  `UPDATE_ON_START`.  
Setting this to `true` should result in Arkmanager updating your server.

Can you please verify? (=

**Comment by Checker8763** [comment]
I have the same problem. The server isn't updateing even if I set the UPDATE_ON_START flag to true.
It seems like arkmanager isn't appling/recognising the flag when run is called.

I was updateing the Server using arkmanager install and then restarted the container.

**Comment by Checker8763** [comment]
It is possible to start the server with `arkmanager start --no-background` to have it running in foregroud and having the convinience of update on start.
Another methode I tried using was setting `arkAutoUpdateOnStart=true` in the arkmanager.cfg but it didn't update either. 
Because it is only applied when starting with `arkmanager start`.

**Comment by Hermsi1337** [comment]
Thanks for pointing that out @Checker8763 ... I will get into this ASAP.

My first idea is adjusting the `entrypoint` to handle `UPDATE_ON_START` and update ark-server.

I'll provide a PR with the required changes. 

Stay tuned <3

**Comment by fwarmuth** [comment]
any progress?

**Comment by Hermsi1337** [comment]
Sorry folks - totally forgot about this one.

I've provided a PR with some changes. Maybe you guys could look at it? (:

If everythings fine, I will merge it.

Thanks and best regards!
