### ISSUE TITLE
The Game.ini is empty

### ISSUE THREAD

**Issue by meisken** [Hermsi1337/docker-ark-server#44]
I supposed the path "/app/server/ShooterGame/Saved/Config/LinuxServer/Game.ini" is where I should go if I want to change some general game configs. But It's empty. 

So I tried to copy my local Game.ini to override it with the command "docker cp Game.ini container_id:/app/server/ShooterGame/Saved/Config/LinuxServer/Game.ini". And I check it with VIM to confirm it has been overridden.

But it turned out the server crashed (no matter I replace it offline or online, even restart the server). So Did I screw up something? Is there any way to change the config? 

![image](https://user-images.githubusercontent.com/38470704/159496206-7292ca81-7856-4936-83cd-50574195831a.png)

![image](https://user-images.githubusercontent.com/38470704/159495749-2fe2c07e-e5f6-4eca-a0fa-d95eb59cbfd1.png)

**Comment by Hermsi1337** [comment]
Hey,

can you provide some logs of the container after changing / reloading the config?

**Comment by meisken** [comment]
The problem is solved. I launched another container. And I copied my local Game.ini to the container. But this time I only restarted the ark server instead of restarting the whole container. And it works fine.
