### ISSUE TITLE
Server not found in Server List

### ISSUE THREAD

**Issue by Skyfay** [Hermsi1337/docker-ark-server#47]
Hey, I set up and started the server. Everything works, it just doesn't appear in the Ark Server list.
If I enter the IP via Steam I can connect without any problems.
I would like to play with Playstation players though, and I don't think they can join via IP.
Can someone tell me why my server doesn't appear in the list?

**Comment by Skyfay** [comment]
In fact, right now that I've sent the message, the server is now visible. However, it took a very, very long time. Is that normal.

**Comment by Hermsi1337** [comment]
Hey @Skyfay,

I'm glad you got your ARK-Server finally up and running.

I can't tell what time-period is called "normal".  
According to my experience, the time differs from 5 to 10 minutes.

Best Regards! (=
