### ISSUE TITLE
Unable to update Server

### ISSUE THREAD

**Issue by Likqez** [Hermsi1337/docker-ark-server#48]
## Server update would not be applied after container exit.

I was unable to update my ark server using [this](https://gist.github.com/Likqez/6d3924bbb263a27a5a6af07075d7092b#file-gistfile1-txt) docker stack.

After executing ``arkmanager update`` the most recent version would be downloaded but lost as the container exited. I was wondering what #6 did change, because I ran a version of the image which already contained the fix. It seems that manual updates still won't work.

**Comment by Likqez** [comment]
# Solution
After I'd set the ``UPDATE_ON_START=true`` the update would be applied properly.

**Comment by Hermsi1337** [comment]
I'm glad you found a solution. Indeed the flag `UPDATE_ON_START` is exactly made for this use-case.

The flag was buggy at the beginning but there were two MR's which fixed it's behavior.

Feel free to re-open the issue, if you have further questions.

Best regards <3
