### ISSUE TITLE
Bad PID

### ISSUE THREAD

**Issue by bla204** [Hermsi1337/docker-ark-server#51]
I have setup this image on a new ubuntu virtual machine.  It successfully downloads the game, but seems unable to start it with some kind of pid issue.

ark_server  | Running command 'run' for instance 'main'
ark_server  | 2022-05-31 01:00:25: start
ark_server  | 2022-05-31 01:00:25: Running /app/server/ShooterGame/Binaries/Linux/ShooterGameServer Genesis\?SessionName=dummyname\?ServerPassword=password\?ServerAdminPassword=password\?MaxPlayers=4\?GameModIds\?GameModIds\?Port=7777\?QueryPort=27015\?RCONEnabled=True\?RCONPort=27020\?listen -log -log
ark_server  | 2022-05-31 01:00:25: Server PID: 240
ark_server  | [S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
ark_server  | Setting breakpad minidump AppID = 346110
ark_server  | 2022-05-31 01:02:06: server is up
ark_server  | /usr/local/bin/arkmanager: line 998:   240 Killed                  "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
ark_server  | 2022-05-31 01:03:25: Bad PID ''; expected '240'
ark_server  | 2022-05-31 01:03:25: exited with status 0
ark_server  | 2022-05-31 01:03:25: restarting server
ark_server  | 2022-05-31 01:03:25: Running /app/server/ShooterGame/Binaries/Linux/ShooterGameServer Genesis\?SessionName=alexmaybe\?ServerPassword=marmar\?ServerAdminPassword=marmarmar\?MaxPlayers=4\?GameModIds\?GameModIds\?Port=7777\?QueryPort=27015\?RCONEnabled=True\?RCONPort=27020\?listen -log -log
ark_server  | 2022-05-31 01:03:25: Server PID: 1377
ark_server  | [S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
ark_server  | Setting breakpad minidump AppID = 346110
ark_server  | 2022-05-31 01:05:06: server is up
ark_server  | /usr/local/bin/arkmanager: line 1002:  1377 Killed                  "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"

**Comment by mb132** [comment]
@bla204 you can try monitoring the servers resources while the server is starting. Just had the same error, my server didn't have enough ram.

**Comment by moonpost** [comment]
trying to get this working with Docker Desktop on intel Mac and all files seem to be present (despite error showing now found) and installed, but also getting bad PID errors:

...
Update state (0x101) committing, progress: 100.00 (18785720663 / 18785720663)
Update state (0x101) committing, progress: 100.00 (18785720663 / 18785720663)
Update state (0x101) committing, progress: 100.00 (18785720663 / 18785720663)
Success! App '376030' fully installed.
No crontab set
Running command 'run' for instance 'main'
2022-06-14 15:54:18: start
2022-06-14 15:54:18: Running /app/server/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?SessionName=jwARK\?ServerPassword=###\?ServerAdminPassword=###\?MaxPlayers=20\?GameModIds\?GameModIds\?Port=7777\?QueryPort=27015\?RCONEnabled=True\?RCONPort=27020\?listen -log -log
2022-06-14 15:54:18: Server PID: 135
2022-06-14 15:54:23: Bad PID ''; expected '135'
2022-06-14 15:54:23: exited with status 0
...ensuring rights on /app /home/steam
_______________________________________

# Ark Server - Tue 14 Jun 2022 03:54:25 PM UTC
# UID 1000 - GID 1000
# ARGS 
_______________________________________
Setting up folder and file structure...
Setting up Arkmanager...
...ensuring rights on /app/arkmanager/arkmanager.cfg
...ensuring rights on /app/arkmanager/instances/main.cfg
...ensuring rights on /app/crontab
No crontab set
Running command 'run' for instance 'main'
2022-06-14 15:54:25: start
/usr/local/bin/arkmanager: line 1319: /app/server/ShooterGame/Binaries/Linux/ShooterGameServer: No such file or directory
/usr/local/bin/arkmanager: line 1319: /app/server/ShooterGame/Binaries/Linux/ShooterGameServer: No such file or directory
chown: changing ownership of '/app/server/ShooterGame/Binaries/Linux/ShooterGameServer': No such file or directory
/usr/local/bin/arkmanager: line 1319: /app/server/ShooterGame/Binaries/Linux/ShooterGameServer: No such file or directory
chown: changing ownership of '/app/server/ShooterGame/Binaries/Linux/ShooterGameServer': No such file or directory
2022-06-14 15:54:25: Running /app/server/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?SessionName=jwARK\?ServerPassword=###\?ServerAdminPassword=###\?MaxPlayers=20\?GameModIds\?GameModIds\?Port=7777\?QueryPort=27015\?RCONEnabled=True\?RCONPort=27020\?listen -log -log
2022-06-14 15:54:25: Server PID: 55
2022-06-14 15:54:30: Bad PID ''; expected '55'
2022-06-14 15:54:30: exited with status 0
...ensuring rights on /app /home/steam
... FAILED ENSURING RIGHTS - CONTINUING STARTUP
_______________________________________

# Ark Server - Tue 14 Jun 2022 03:54:33 PM UTC
# UID 1000 - GID 1000
# ARGS 
_______________________________________
Setting up folder and file structure...
Setting up Arkmanager...
...ensuring rights on /app/arkmanager/arkmanager.cfg
...ensuring rights on /app/arkmanager/instances/main.cfg
...ensuring rights on /app/crontab
No crontab set
Running command 'run' for instance 'main'
2022-06-14 15:54:33: start
2022-06-14 15:54:33: Running /app/server/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?SessionName=jwARK\?ServerPassword=###\?ServerAdminPassword=###\?MaxPlayers=20\?GameModIds\?GameModIds\?Port=7777\?QueryPort=27015\?RCONEnabled=True\?RCONPort=27020\?listen -log -log
2022-06-14 15:54:33: Server PID: 55
2022-06-14 15:54:38: Bad PID ''; expected '55'
2022-06-14 15:54:38: exited with status 0
...ensuring rights on /app /home/steam

**Comment by tctfox** [comment]
What does this line even mean
ark_server | [S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Is the server now up or not? I am a bit confused by that

**Comment by tctfox** [comment]
@Hermsi1337 
True I was able to totally ignore it. The server works really good, thanks :)
