### ISSUE TITLE
Invalid Authentication Token / Timeout even though the server is up and running

### ISSUE THREAD

**Issue by schmaenjael** [Hermsi1337/docker-ark-server#53]
### Greetings! 👋 

I was running you docker image a before the update hit and I had no problems running it. Now that I switched to "Fjordur" or the "Viking_P" map, the server neither takes any configuration I provide using the environment variables nor am I able to connect to the server. 
My group, including me, always gets the same error message and none of us are able to connect to the server. 

My docker-compose.yml file:

```yml
version: '3.2'

services:
  server:
    restart: always
    container_name: ark_server
    image: hermsi/ark-server:latest
    volumes:
      - /home/manni/ark/ark-server:/app
      - /home/manni/ark/ark-server-backups:/home/steam/ARK-Backups
    environment:
      - SESSION_NAME=test_server
      - SERVER_MAP=Viking_P
      - SERVER_PASSWORD=test1234
      - ADMIN_PASSWORD=test1334
      - MAX_PLAYERS=20
      - ENABLE_CROSSPLAY=true
    ports:
      - "7777:7777/udp"
      - "7778:7778/udp"
      - "27020:27020/tcp"
      - "27015:27015/udp"
    networks:
      - default
```

Looking into the logs, I noticed that the Steam API has problems connecting:
```sh
 Update state (0x101) committing, progress: 99.37 (18667077408 / 18785720663)
Success! App '376030' fully installed.
No crontab set
Running command 'run' for instance 'main'
2022-06-14 19:34:31: start
2022-06-14 19:34:31: Running /app/server/ShooterGame/Binaries/Linux/ShooterGameServer Viking_P\?SessionName=lawful_evil\?ServerPassword=abcd1234\?ServerAdminPassword=abcd1443\?MaxPlayers=20\?GameModIds\?GameModIds\?Port=7777\?QueryPort=27015\?RCONEnabled=True\?RCONPort=27020\?listen -log -crossplay -log
2022-06-14 19:34:31: Server PID: 180
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
2022-06-14 19:34:37: server is up
...ensuring rights on /app /home/steam
_______________________________________

# Ark Server - Wed 15 Jun 2022 08:20:33 AM UTC
# UID 1000 - GID 1000
# ARGS --arkopt,-crossplay 
_______________________________________
Setting up folder and file structure...
Setting up Arkmanager...
...ensuring rights on /app/arkmanager/arkmanager.cfg
...ensuring rights on /app/arkmanager/instances/main.cfg
...ensuring rights on /app/crontab
No crontab set
Running command 'run' for instance 'main'
2022-06-15 08:20:34: start
2022-06-15 08:20:34: Running /app/server/ShooterGame/Binaries/Linux/ShooterGameServer Viking_P\?SessionName=lawful_evil\?ServerPassword=abcd1234\?ServerAdminPassword=abcd1443\?MaxPlayers=20\?GameModIds\?GameModIds\?Port=7777\?QueryPort=27015\?RCONEnabled=True\?RCONPort=27020\?listen -log -crossplay -log
2022-06-15 08:20:34: Server PID: 55
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
2022-06-15 08:20:39: server is up
```
but even though the SteamAPI initialization failed, arkmanager status gives me the following result:
(Also notice the wrong amount of max players)

```sh
╭ manni@Server in ~/ark took 181ms
╰ π  docker exec ark_server arkmanager status

Running command 'status' for instance 'main'
 Server running:   Yes 
 Server PID:   55 
 Server listening:   Yes 
Server Name: Manni - (v346.12)
Steam Players: 0 / 70
Active Steam Players: 0
 Server online:   Yes 
 ARKServers link:   http://arkservers.net/server/[IP]:27015 
 Steam connect link:   steam://connect/[IP]:27015 
 Server build ID:   8929064 
 Server version:   346.12 
```

and it also displays in the Steam Server list:

![grafik](https://user-images.githubusercontent.com/63205793/173883652-675c7ade-ea60-4a82-a5f0-1352435a33a0.png)

I am running this container on the following dedicated server:

OS: Ubuntu 22.04 LTS x86_64 
Kernel: 5.15.0-33-generic 
CPU: AMD Ryzen 5 3600 (12) @ 3.600GHz 
GPU: 2b:00.0 ASPEED Technology, Inc. ASPEED Graphics Family 
Memory: 64234MiB 
UFW: disabled

If you need any further informations, feel free to write me - I'll make sure to respond quickly, also thanks for helping us out!
Looking forward to hearing from you!

~ Manni

**Comment by Melethainiel** [comment]
Hey,

You get this error when the map is not recognized. You can see Map : ShooterEntry.
For the last map you should set  `SERVER_MAP=Fjordur`

**Comment by Hermsi1337** [comment]
Hey m8,

the "Error" is not really an error - see here: https://github.com/GameServerManagers/LinuxGSM/discussions/3405#discussioncomment-553757

> That's not an error. You can ignore it. It's just saying that the steam client isn't running. Which is fine since you are using it as a server.

I just tried to setup a Server with the `Viking_P` map and connected successfully. Did you change the map after installing or set it directly upon install?

**Comment by schmaenjael** [comment]
> You get this error when the map is not recognized. You can see Map : ShooterEntry.

Sure, I'll try it out. Though "Viking_P" is the Server map name according to https://ark.fandom.com/wiki/Mod:Fjordur!

**Comment by Melethainiel** [comment]
That's the old name when it was an item from the workshop (for what I understood)
I'm running the server fine with the setting I gave you. I hope it will work for you too !

**Comment by schmaenjael** [comment]
@Hermsi1337 & @Melethainiel Thanks for both of your time and help!

I was able to resolve the error by applying @Melethainiel's comment to switch to the new map name `Fjordur` instead of using `Viking_P`. Thanks again, I would not have guessed that they switched the name after it became official! 😅 

Thanks again, I'll close this issue now!

**Comment by Melethainiel** [comment]
I'm glad I could help

**Comment by alex4401** [comment]
> Sure, I'll try it out. Though "Viking_P" is the Server map name according to https://ark.fandom.com/wiki/Mod:Fjordur!

FYI, use https://ark.wiki.gg/Fjordur for that now. Fandom's no longer considered the official wiki (since April).
