### ISSUE TITLE
Files install, but won't run; bad PID?

### ISSUE THREAD

**Issue by moonpost** [Hermsi1337/docker-ark-server#54]
trying to get this working with Docker Desktop on intel Mac (never installed before) and all files seem to be present in their proper folder structures (despite error showing not found), but also getting bad PID errors:

...
Update state (0x101) committing, progress: 100.00 (18785720663 / 18785720663)
Update state (0x101) committing, progress: 100.00 (18785720663 / 18785720663)
Update state (0x101) committing, progress: 100.00 (18785720663 / 18785720663)
Success! App '376030' fully installed.
No crontab set
Running command 'run' for instance 'main'
2022-06-14 15:54:18: start
2022-06-14 15:54:18: Running /app/server/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland?SessionName=jwARK?ServerPassword=###?ServerAdminPassword=###?MaxPlayers=20?GameModIds?GameModIds?Port=7777?QueryPort=27015?RCONEnabled=True?RCONPort=27020?listen -log -log
2022-06-14 15:54:18: Server PID: 135
2022-06-14 15:54:23: Bad PID ''; expected '135'
2022-06-14 15:54:23: exited with status 0
...ensuring rights on /app /home/steam

# Ark Server - Tue 14 Jun 2022 03:54:25 PM UTC
# UID 1000 - GID 1000
# ARGS 

Setting up folder and file structure...
Setting up Arkmanager...
...ensuring rights on /app/arkmanager/arkmanager.cfg
...ensuring rights on /app/arkmanager/instances/main.cfg
...ensuring rights on /app/crontab
No crontab set
Running command 'run' for instance 'main'
2022-06-14 15:54:25: start
/usr/local/bin/arkmanager: line 1319: /app/server/ShooterGame/Binaries/Linux/ShooterGameServer: No such file or directory
/usr/local/bin/arkmanager: line 1319: /app/server/ShooterGame/Binaries/Linux/ShooterGameServer: No such file or directory
chown: changing ownership of '/app/server/ShooterGame/Binaries/Linux/ShooterGameServer': No such file or directory
/usr/local/bin/arkmanager: line 1319: /app/server/ShooterGame/Binaries/Linux/ShooterGameServer: No such file or directory
chown: changing ownership of '/app/server/ShooterGame/Binaries/Linux/ShooterGameServer': No such file or directory
2022-06-14 15:54:25: Running /app/server/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland?SessionName=jwARK?ServerPassword=###?ServerAdminPassword=###?MaxPlayers=20?GameModIds?GameModIds?Port=7777?QueryPort=27015?RCONEnabled=True?RCONPort=27020?listen -log -log
2022-06-14 15:54:25: Server PID: 55
2022-06-14 15:54:30: Bad PID ''; expected '55'
2022-06-14 15:54:30: exited with status 0
...ensuring rights on /app /home/steam
... FAILED ENSURING RIGHTS - CONTINUING STARTUP

# Ark Server - Tue 14 Jun 2022 03:54:33 PM UTC
# UID 1000 - GID 1000
# ARGS 

Setting up folder and file structure...
Setting up Arkmanager...
...ensuring rights on /app/arkmanager/arkmanager.cfg
...ensuring rights on /app/arkmanager/instances/main.cfg
...ensuring rights on /app/crontab
No crontab set
Running command 'run' for instance 'main'
2022-06-14 15:54:33: start
2022-06-14 15:54:33: Running /app/server/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland?SessionName=jwARK?ServerPassword=###?ServerAdminPassword=###?MaxPlayers=20?GameModIds?GameModIds?Port=7777?QueryPort=27015?RCONEnabled=True?RCONPort=27020?listen -log -log
2022-06-14 15:54:33: Server PID: 55
2022-06-14 15:54:38: Bad PID ''; expected '55'
2022-06-14 15:54:38: exited with status 0
...ensuring rights on /app /home/steam

--------------

and here is my docker-compose file:

version: '3'

services:
  server:
    restart: always
    container_name: ark_server_island
    image: hermsi/ark-server:latest
    volumes:
      - /Users/jwilker/Documents/dockerark:/app
      - /Users/jwilker/Documents/gamebackups/arkserver-backup:/home/steam/ARK-Backups
    environment:
      - SESSION_NAME=jwARK
      - SERVER_MAP=TheIsland
      - SERVER_PASSWORD=###
      - ADMIN_PASSWORD=###
      - MAX_PLAYERS=10
      - UPDATE_ON_START=false
      - BACKUP_ON_STOP=true
      - PRE_UPDATE_BACKUP=true
      - WARN_ON_STOP=true
    ports:
      # Port for connections from ARK game client
      - "7777:7777/udp"
      # Raw UDP socket port (always Game client port +1)
      - "7778:7778/udp"
      # RCON management port
      - "27020:27020/tcp"
      # Steam's server-list port
      - "27015:27015/udp"
    networks:
      - default

**Comment by moonpost** [comment]
also just a note that I'm new to docker, but have Valheim and Minecraft servers successfully running.

**Comment by Melethainiel** [comment]
Do you have at least 20gb free on your volume ?

**Comment by moonpost** [comment]
I have like 50 GB free after all the folders/files are installed so I would think that'd be good, no? for reference, after the install and failure, like I said, I see all the folders/files and that takes up about 18.79 GB.

**Comment by moonpost** [comment]
huh. ok, just ran it again since clearly all the files are there and now it is running seemingly fine. maybe I just needed a reset or something? I'll see if it stays stable and playable but for right now it is working! Thanks!
