### ISSUE TITLE
Steam User Account 

### ISSUE THREAD

**Issue by BloxBoss6** [Hermsi1337/docker-ark-server#58]
I've been looking through your docker compose file, the code itself, and even into the ark-server-tools code and documentation. I know that steamcmd requires a steam user account at least at first in order to get all the dlc that the user has. But you have no way of changing that. Am I missing something or is this something that can be fixed?

Thanks

**Comment by Hermsi1337** [comment]
Hey @BloxBoss6,

I've did a major refactoring to this image including a change which enables you to add your own steam-login.

`quay.io/hermsi1337/ark-server:refactor`

See here for docs: https://github.com/Hermsi1337/docker-ark-server/blob/task/use-steamcmd-img/README.md#configure-steam-login-session

I'd appreciate your feedback!

**Comment by Hermsi1337** [comment]
This should be fixed by #57 ... try using the current `latest`-img.

Feel free to open if you have any issues (= 


Regards

**Comment by Hermsi1337** [comment]
@BloxBoss6 did you manage to use this image with your own login?

**Comment by BloxBoss6** [comment]
I haven't actually tried, I didn't realize the free dlcs we're already downloaded by default, so before you got back to me I got my server running. I can try either tonight or tomorrow and see if I get the same issue

**Comment by Hermsi1337** [comment]
nvmd.. I've created more detailed docs on how to use a custom steam-login:

https://github.com/Hermsi1337/docker-ark-server#configure-steam-login-session
