### ISSUE TITLE
Cannot seem to set a password

### ISSUE THREAD

**Issue by woeisme** [Hermsi1337/docker-ark-server#59]
The documentation leaves it very unclear where to set a Server / ServerAdmin password.

I've experimented with setting it in docker-compose.yml or /ark-server/server/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini but neither seems to be working. 

it would also be useful to know how to set exclusivejoin (whitelist) on the container.

**Comment by Hermsi1337** [comment]
This should be fixed by #57 ... try using the current `latest`-img.

Feel free to open if you have any issues (= 


Regards

**Comment by ermerica** [comment]
Hello,

I currently have this issue when using the :latest image. No environment variables are used when loading with the docker-compose script provided.

Thanks!
