### ISSUE TITLE
invalid Steam_user in config file

### ISSUE THREAD

**Issue by ehcorn** [Hermsi1337/docker-ark-server#64]
this occurred when I tried running arkmanager update to get the newest version, when I start the server and run arkmanager status it just shows "Invalid steamcmd_user in config file" and I'm using the default config, anonymous login. Server's been rock solid until this last update today.

**Comment by Hermsi1337** [comment]
Hey m8, try this: https://github.com/Hermsi1337/docker-ark-server/issues/63#issuecomment-1171583880

I will document it asap or change the dockerfile again if this is a Thing.

**Comment by ehcorn** [comment]
I've added the STEAM_LOGIN to the environment and that seems to have taken it, but hasn't seemed to help. I'm doing a nuke and re-run but I'm running this on a synology so installing steam isn't something I'm interested in trying.

**Comment by timmermansjoy** [comment]
yep same issue here

**Comment by Hermsi1337** [comment]
I've updated the `README.md` regarding the usage of `arkmanager`: https://github.com/Hermsi1337/docker-ark-server#tweak-configuration

The usage of `STEAM_LOGIN` is discussed here: https://github.com/Hermsi1337/docker-ark-server/issues/58

**Comment by timmermansjoy** [comment]
Okay so I have to install steam on my server just to make it work again? 

could you elaborate on why this refactor took place to add dependancies outside of docker?

**Comment by Hermsi1337** [comment]
What do you mean by dependencies outside of docker?

The thing with `STEAM_LOGIN` is, that you need a valid session to interact with your account using `steamcmd`.

In general the session could be created by doing a `steamcmd +login username` and your password.  
But as soon as you've guarded your steam-account using `steamguard` or any 2fa-mechanism it's not possible to programmatically create a session for your steam-user.

Therefore you'll need to create a steam-session manually and mount it inside the container.  
But that does not require steam installed on your local machine. You can also create the session in the container.

I'll do some documentation on this and get back to you.

See here for some explanation on this: https://github.com/CM2Walki/steamcmd#how-to-use-this-image
