### ISSUE TITLE
Server doesn't allow connections - times out

### ISSUE THREAD

**Issue by jgreuling** [Hermsi1337/docker-ark-server#7]
I've gotten as far as creating a compose file and spinning the container up; the server appears correctly on the server list but doesn't allow anyone to connect.

On the first attempt I see the loading screen with "PrimalGameData_BP" before I'm bounced back to the server list and it eventually fails with error "Connection Timeout."

I can see the days incrementing on the server, so it appears to be up & running.

I've also tried connecting directly to the server over my local network and have the same issue.

Am in the process of troubleshooting, but I've spent a few hours and had no luck. I'm not sure if there's a configuration value that maybe is not getting set properly somewhere?

**Comment by jgreuling** [comment]
Compose file:

version: "3"
volumes:
  rj-ark-theisland-data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/u01/games/rj-ark/worlds/rj-theisland"
services:
  rj-ark-theisland:
    image: hermsi/ark-server:latest
    environment:
      - SESSION_NAME=rj-theisland
      - SERVER_MAP=TheIsland
      - SERVER_PASSWORD=
      - ADMIN_PASSWORD=<PASSWORD>
      - MAX_PLAYERS=20
      - UPDATE_ON_START=true
      - GAME_CLIENT_PORT=7778
      - RCON_PORT=27020
      - SERVER_LIST_PORT=27015
    ports:
      - 7778:7778/udp
      - 27015:27015/udp
      - 27020:27020/tcp
    networks:
      - default
    volumes:
      - rj-ark-theisland-data:/app

**Comment by jgreuling** [comment]
I found the cause of the problem.

It appears that even though GAME_CLIENT_PORT is specified as 7778 in my compose file it is still utilizing 7777.

Final ports that worked:
ports:
 - 7777:7777/udp
 - 27015:27015/udp
 - 27020:27020/tcp

**Comment by Hermsi1337** [comment]
Hey M8,

I'm glad that you already figured out the solution.

Unfortunately the `_PORT`-envs are quite missleading because it's not possible to change them. (for this image at least)  
Sticking to the default-ports is for now the best/safest way to get your own ARK-server up and running.

Feel free to reopen this issue if you have any further questions !

Best Regards <3

**Comment by Hermsi1337** [comment]
Hey M8,

I'm glad that you already figured out the solution.

I've fixed the wrong port-specs inside the `docker-compose.yml` and the `Dockerfile`.  
Thanks for pointing it out.

In case you want to run multiple ARK-Server on the same port I recommend these docs: https://ark.fandom.com/wiki/Dedicated_server_setup#Network
