### ISSUE TITLE
Unable to specify -exclusivejoin

### ISSUE THREAD

**Issue by obsessionwithfire** [Hermsi1337/docker-ark-server#76]
Adding exclusivejoin=true as an env variable appears to be ignored on startup.

**Comment by Hermsi1337** [comment]
Hey @obsessionwithfire, could you share a bit more of your configuartion (e.g.` docker-compose.yml`).

Also, please provide startup-logs with env  `DEBUG=true`.

Thanks!

**Comment by woeisme** [comment]
> Adding exclusivejoin=true as an env variable appears to be ignored on startup.

I've had success with the following:
`services:
  server:
    restart: always
    container_name: ark
    image: hermsi/ark-server:latest
    command: --arkopt,-exclusivejoin --arkopt,-UseVivox
    volumes:
`

**Comment by Hermsi1337** [comment]
The solution provided by @woeisme is correct and should work flawlessly.

Feel free to reopen if you have any issues.
