### ISSUE TITLE
Docker Compose file giving PID errors

### ISSUE THREAD

**Issue by FireInferno1** [Hermsi1337/docker-ark-server#77]
Hello

I'm a bit familiar with docker containers. I basically took the docker-compose.yml file that you posted in your example, changed the mount directory and stuff about the session (password/name). I'm now getting errors in docker that reference "bad PID ' '; expected '107'". As well while watching the server start, it goes pas the update state, verifying install, then warns "Your ark server exec could not be found"

Could anyone be of assistance?

**Comment by FireInferno1** [comment]
Oh I ended up figuring it out, there wasn't enough space and I was getting a 0x202 error. I made a new VM and remade the docker container and it's working as expected

**Comment by Hermsi1337** [comment]
I'm glad you figured it out. I've not managed to throw a proper error when there is not enough diskspace left yet.

https://github.com/Hermsi1337/docker-ark-server/issues/74

I'll let you know there, as soon as I've done it (=
