### ISSUE TITLE
Can't connect to server from Epic client, at all

### ISSUE THREAD

**Issue by bonny1992** [Hermsi1337/docker-ark-server#81]
Good day everyone!

I'm currently trying to set up a server for my gf and me to play the game now that Epic gifted the game.
The issue is that no matter what I can't get to connect to the server at all.

Here you can find my `docker run` command:
```
docker run -d  \
	--name=ark-server  \
	--restart=unless-stopped  \
	-e SESSION_NAME="Bonny" \
	-e ADMIN_PASSWORD="[redacted]" \
	-e MAX_PLAYERS="2" \
	-e SERVER_PASSWORD="[redacted]" \
	-e ENABLE_CROSSPLAY="true" \
	-e DISABLE_BATTLEYE="true" \
	-e PGID=1001 -e PUID=1000  \
	-v /mnt/local/Games/Ark:/app \
	-v /etc/localtime:/etc/localtime:ro  \
	-p 7777:7777/udp \
        -p 7778:7778/udp \
        -p 27015:27015/udp \
        -p 27020:27020/udp \
    hermsi/ark-server:latest \
		--arkopt,-epiconly --arkopt,-UseVivox
```
I've tried before without adding `-epiconly` but to no avail. (added as @woeisme's reply [here](https://github.com/Hermsi1337/docker-ark-server/issues/76#issuecomment-1233343124))

Here's the logs from the last run, with `DEBUG` set as true:
[logs.txt](https://github.com/Hermsi1337/docker-ark-server/files/9639043/logs.txt)

Ark says connection timeout everytime (starting a single player game, then TAB -> `open ip:7777`). Instead, Steam and ArkServers are able to reach the server and list the stuff (if `-epiconly` is off, of course).
![Steam server status](https://i.imgur.com/dBFdrFg.png "Steam server status window")

Can you help me?

**Comment by EverLab** [comment]
I have same problem, i cannot join the server with Epic Ark game... I didn't see him in search and when i try to connect throught console that didn't work.

**Comment by bonny1992** [comment]
Good news: Today the server appeared into the "Non official" server list, finally.
Honestly I don't know if something changed or it was the time passed (more than 24h) but I'll post my server' specs to put it into perspective:
```
AMD Ryzen™ 5 3600
64 GB DDR4
2 x 512 GB SSD NVMe
```

Hermsi, all in all this is a very good docker image :P

**Comment by Hermsi1337** [comment]
I'm glad you figured at out! TBH I've also noticed that the time until the server becomes joinable is very random.. but 24h is by far the longest time

**Comment by bonny1992** [comment]
It's probably something on the Ark side.

It's not 24h in total tho, it's just that I checked 24h later.

**Comment by bonny1992** [comment]
> > It's probably something on the Ark side.
> > It's not 24h in total tho, it's just that I checked 24h later.
> 
> I also meeting the same problem, steam and ark server display normal, but epic can't found it, wait to check

I think this time you have to update the server.

Running `docker exec -u steam ark-server arkmanager update --force` did not do the trick to me, I had to remove the docker container and add the environment variable `UPDATE_ON_START="true"`. As soon as I did this the server updated and I started seeing the server in the list again.

**Comment by 0honus0** [comment]
> > > It's probably something on the Ark side.
> > > It's not 24h in total tho, it's just that I checked 24h later.
> > 
> > 
> > I also meeting the same problem, steam and ark server display normal, but epic can't found it, wait to check
> 
> I think this time you have to update the server.
> 
> Running `docker exec -u steam ark-server arkmanager update --force` did not do the trick to me, I had to remove the docker container and add the environment variable `UPDATE_ON_START="true"` to my `run` command. As soon as I did this the server updated and I started seeing the server in the list again.

it works
