### ISSUE TITLE
GameUserSettings.ini get overwritten on server start.

### ISSUE THREAD

**Issue by Mickroz** [Hermsi1337/docker-ark-server#90]
Everytime i start the server, the GameUserSettings.ini gets overwritten with default settings.

**Comment by Mickroz** [comment]
ok, for some reason all my enviroment setttings were gone, its all god now.

**Comment by alexweininger** [comment]
I'm running into the same issue, do you know how you fixed it?

**Comment by Mickroz** [comment]
I set my basic enviroment settings in the docker  stack im using, they were missing for some reason, those are the only one i saw got changed tbh, haven't played on the server in a while.
https://github.com/Hermsi1337/docker-ark-server#basic-configuration
